# numpy 数组对象 ndarry

## 创建

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [4]:
print(" arr2.shape:\t", arr2.shape)
print(" arr2.dtype:\t", arr2.dtype)
print(" arr2.size:\t", arr2.size)
print(" arr2.itemsize:\t", arr2.itemsize)

 arr2.shape:	 (3, 5)
 arr2.dtype:	 int32
 arr2.size:	 15
 arr2.itemsize:	 4


### 重新设置 shape

只改变了每个轴的大小，并未改变顺序，不是转置

In [5]:
arr2.shape = 5,3
print(arr2)

[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]
 [3 4 5]]


In [7]:
print(np.arange(0,1,0.1))

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]


In [8]:
print(np.linspace(0,1,10))

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]


In [17]:
print(np.logspace(1,2,5))# 从10^1到10^2的5个点

[  10.           17.7827941    31.6227766    56.23413252  100.        ]


In [18]:
print(np.zeros((2,3)))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [19]:
print(np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [21]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
np.ones((5,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

## 数组数据类型

In [23]:
np.float64(10)

10.0

In [24]:
np.int8(10.0)

10

In [25]:
np.bool(10)

True

In [26]:
np.float(False)

0.0

### 创建数据类型

In [28]:
df = np.dtype([("name", np.str_,40), ("numitems", np.int64), ("price", np.float64)])
print("数据类型", df)

数据类型 [('name', '<U40'), ('numitems', '<i8'), ('price', '<f8')]


In [29]:
print(df["name"])

<U40


In [30]:
print(np.dtype(df["name"]))

<U40


### 自定义数组数据

In [32]:
itemz = np.array([("tomatoes", 42, 4.14), ("cabbages", 13, 1.72)], dtype=df)
print('自定义数据: \t', itemz)

自定义数据: 	 [('tomatoes', 42, 4.14) ('cabbages', 13, 1.72)]


### 生成随机数

In [33]:
np.random.random(10)

array([ 0.37407571,  0.90529456,  0.75675266,  0.42802253,  0.93561297,
        0.20494106,  0.4009724 ,  0.90783854,  0.1213847 ,  0.10868184])

In [34]:
print("均匀分布随机数")
np.random.rand(10,5)

均匀分布随机数


array([[ 0.16726227,  0.74040838,  0.13695204,  0.17403158,  0.07027201],
       [ 0.41229891,  0.95933807,  0.74558486,  0.51348803,  0.13452694],
       [ 0.89367905,  0.61829163,  0.54529022,  0.53628797,  0.03075226],
       [ 0.26016588,  0.29324927,  0.61961713,  0.59725844,  0.59443278],
       [ 0.2157677 ,  0.39940338,  0.0923325 ,  0.35088972,  0.55961505],
       [ 0.46504666,  0.57216539,  0.54415829,  0.82848913,  0.77084555],
       [ 0.71163826,  0.12468075,  0.27906012,  0.89808225,  0.22830871],
       [ 0.90541626,  0.48796726,  0.21718689,  0.52785294,  0.54453626],
       [ 0.19153182,  0.39942999,  0.35324208,  0.71803467,  0.97514028],
       [ 0.67492791,  0.75585194,  0.97937117,  0.32390308,  0.47715445]])

In [35]:
print("正态分布")
np.random.randn(3, 2)

正态分布


array([[-1.43696207,  1.50928099],
       [ 0.79981092,  1.05101004],
       [-0.69666433,  0.0357439 ]])

In [36]:
print("上下限")
np.random.randint(low=1, high=10, size=[2, 5])

上下限


array([[9, 3, 6, 3, 3],
       [7, 2, 1, 8, 8]])

##  访问

In [37]:
arr = np.arange(10)
arr[5]

5

In [38]:
arr[3:5]

array([3, 4])

In [39]:
arr[:5]

array([0, 1, 2, 3, 4])

In [40]:
arr[-1]

9

In [41]:
arr[2:4]=100,101
arr

array([  0,   1, 100, 101,   4,   5,   6,   7,   8,   9])

In [42]:
print("第三个参数表示步长")
arr[1:-1:2]

第三个参数表示步长


array([  1, 101,   5,   7])

In [43]:
arr[5:1:-2]

array([  5, 101])

In [45]:
print("多维数组")
arr = np.array([np.linspace(1,5,5), np.linspace(4,8,5), np.linspace(7,11,5), ])
arr

多维数组


array([[  1.,   2.,   3.,   4.,   5.],
       [  4.,   5.,   6.,   7.,   8.],
       [  7.,   8.,   9.,  10.,  11.]])

In [46]:
arr[1,3:5]

array([ 7.,  8.])

In [47]:
arr[1:, 2:]

array([[  6.,   7.,   8.],
       [  9.,  10.,  11.]])

In [48]:
arr[:,2]

array([ 3.,  6.,  9.])

### 整数函数 和 布尔值索引 访问

In [49]:
arr[(0,1,2), (1,2,3)]

array([  2.,   6.,  10.])

In [50]:
arr[1:,(0,2,3)]

array([[  4.,   6.,   7.],
       [  7.,   9.,  10.]])

In [51]:
mask = np.array([1,0,1],dtype=np.bool)
arr[mask, 2]

array([ 3.,  9.])

### 改变数组形状

In [53]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
arr.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
arr.reshape(3, 4).ndim  # 数组维度

2

### ravel  flatten 函数  展平数组

In [56]:
arr = np.arange(12).reshape(3, 4)
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
arr.flatten() # 横向

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
arr.flatten('F') # 纵向

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### 数组组合

In [71]:
arr1 = np.arange(12).reshape(3,4)
arr2 =  arr1*3
print("arr1:\n", arr1)
print("arr2:\n", arr2)

arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr2:
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [63]:
np.hstack((arr1, arr2)) # 横向组合

array([[ 0,  1,  2,  3,  0,  3,  6,  9],
       [ 4,  5,  6,  7, 12, 15, 18, 21],
       [ 8,  9, 10, 11, 24, 27, 30, 33]])

In [64]:
np.vstack((arr1, arr2)) # 纵向组合

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [65]:
np.concatenate((arr1, arr2), axis=1)

array([[ 0,  1,  2,  3,  0,  3,  6,  9],
       [ 4,  5,  6,  7, 12, 15, 18, 21],
       [ 8,  9, 10, 11, 24, 27, 30, 33]])

In [66]:
np.concatenate((arr1, arr2), axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

### 数组分割

In [67]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
np.hsplit(arr,2) # 横向分割

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [69]:
np.vsplit(arr,2) # 纵向分割

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [70]:
    print("横向分割：\n", np.split(arr,2, axis=1))
    print("纵向分割：\n", np.split(arr,2, axis=0))

横向分割：
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
纵向分割：
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# 函数

## 创建矩阵

In [72]:
matri1 = np.mat("1 2 3;4 5 6; 7 8 9")
matri1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
matr2 = np.matrix([[1,2,3],[4,5,6], [7,8,9]])
matr2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### bmat  分块矩阵

In [74]:
arr1 = np.eye(3)
arr1

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [75]:
arr2 = 3*arr1
arr2

array([[ 3.,  0.,  0.],
       [ 0.,  3.,  0.],
       [ 0.,  0.,  3.]])

In [76]:
np.bmat("arr1 arr2;arr1 arr2")

matrix([[ 1.,  0.,  0.,  3.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  3.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  3.],
        [ 1.,  0.,  0.,  3.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  3.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  3.]])

### 矩阵运算

In [77]:
matr1 = np.mat("1 2 3;4 5 6; 7 8 9")
matr2 = matr2*3
matr2

matrix([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]])

In [78]:
matr1 + matr2

matrix([[ 4,  8, 12],
        [16, 20, 24],
        [28, 32, 36]])

In [79]:
matr1 - matr2

matrix([[ -2,  -4,  -6],
        [ -8, -10, -12],
        [-14, -16, -18]])

In [80]:
matr1*matr2 # 此处新建矩阵用的不是array而是mat

matrix([[ 90, 108, 126],
        [198, 243, 288],
        [306, 378, 450]])

In [81]:
np.multiply(matr1, matr2)

matrix([[  3,  12,  27],
        [ 48,  75, 108],
        [147, 192, 243]])

In [83]:
matr1.dot(matr2)

matrix([[ 90, 108, 126],
        [198, 243, 288],
        [306, 378, 450]])

- T   转置
- H   共轭转置
- I   逆
- A   二维数组视图

In [87]:
matr1.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [88]:
matr1.H

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [89]:
matr1.I

matrix([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
        [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
        [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

In [90]:
matr1.A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## ufunc函数

In [91]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x+y

array([5, 7, 9])

In [92]:
x-y

array([-3, -3, -3])

In [93]:
x*y

array([ 4, 10, 18])

In [94]:
x/y

array([ 0.25,  0.4 ,  0.5 ])

In [95]:
x**y

array([  1,  32, 729], dtype=int32)

In [96]:
x = np.array([1,3,5])
y = np.array([2,3,4])

In [97]:
x<y

array([ True, False, False], dtype=bool)

In [99]:
x==y

array([False,  True, False], dtype=bool)

In [100]:
x>=y

array([False,  True,  True], dtype=bool)

In [101]:
x!=y

array([ True, False,  True], dtype=bool)

### 逻辑运算

In [102]:
np.all(x==y)

False

In [103]:
np.any(x==y)

True

### 广播机制 ==》 两个数组shape不一致采用
    

- 输入数组向最长数组shape看齐，shape不足在前面补1
    - 输入数组的shape是输入数组的各个轴上的最大值
    - 

In [106]:
arr1 = np.array([[0,0,0], [1,1,1], [2,2,2], [3,3,3]])
arr1

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [107]:
arr1.shape

(4, 3)

In [108]:
arr2 = np.array([1,2,3])

In [109]:
arr2.shape

(3,)

In [110]:
arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

```
0, 0, 0   +   1, 2, 3    =    1, 2, 3 
1, 1, 1   +   1, 2, 3    =    2, 3, 4 
2, 2, 2   +   1, 2, 3    =    3, 4, 5 
3, 3, 3   +   1, 2, 3    =    4, 5, 6 
```

In [112]:
arr2 = np.array([1,2,3,4]).reshape((4,1))
arr2

array([[1],
       [2],
       [3],
       [4]])

In [113]:
arr2.shape

(4, 1)

In [114]:
arr1+arr2

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

 ```
0, 0, 0   +   1, 1, 1    =    1, 1, 1
1, 1, 1   +   2, 2, 3    =    3, 3, 3
2, 2, 2   +   3, 3, 3    =    5, 5, 5
3, 3, 3   +   4, 4, 4    =    7, 7, 7
```

# 统计分析

## 读写文件

np.save(file, arr, allow_pickle=True, fix_imports=True)
- file 要保存的文件名
- arr  要保存的数组
- 存储结果为npy格式

In [117]:
import os
# 1、os.path.exists(path) 判断一个目录是否存在
# 2、os.makedirs(path) 多层创建目录
# 3、os.mkdir(path) 创建目录
arr = np.arange(100).reshape(10,10)
path = "./numpy_file_test"
if not(os.path.exists(path)):
    os.mkdir("./numpy_file_test")
np.save("./numpy_file_test/save_arr", arr)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [119]:
arr2 = np.arange(0,1,0.1)
np.savez("./numpy_file_test/savez_arr",arr1, arr2)

In [120]:
loaded_data = np.load("./numpy_file_test/save_arr.npy")
loaded_data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
loaded_data = np.load("./numpy_file_test/savez_arr.npz")
loaded_data["arr_0"]

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [123]:
loaded_data["arr_1"]

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

np.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ')
- fname 文件名
- X 数组数据
- delimiter 分隔符

In [128]:
arr = np.arange(0,12,0.5).reshape(4,-1)
np.savetxt("./numpy_file_test/arr.txt", arr, fmt="%d", delimiter=',')
loaded_data = np.loadtxt("./numpy_file_test/arr.txt", delimiter=',')
loaded_data

array([[  0.,   0.,   1.,   1.,   2.,   2.],
       [  3.,   3.,   4.,   4.,   5.,   5.],
       [  6.,   6.,   7.,   7.,   8.,   8.],
       [  9.,   9.,  10.,  10.,  11.,  11.]])

- 排序

In [129]:
np.random.seed(20)
arr = np.random.randint(1,10,size=10)
arr

array([4, 5, 7, 8, 3, 1, 7, 9, 6, 4])

In [136]:
print(np.sort(arr))

[1 3 4 4 5 6 7 7 8 9]


In [138]:
arr = np.random.randint(1,10,size=(3,3))
print(arr)
np.sort(arr, axis = 1)

[[4 4 1]
 [7 3 4]
 [2 9 1]]


array([[1, 4, 4],
       [3, 4, 7],
       [1, 2, 9]])

In [139]:
np.sort(arr, axis = 0)

array([[2, 3, 1],
       [4, 4, 1],
       [7, 9, 4]])

- argsort 排序后的索引值

In [140]:
arr = np.random.randint(1,10,size=10)
print(arr)
print(np.argsort(arr))

[3 8 7 7 9 3 2 4 3 7]
[6 0 5 8 7 2 3 9 1 4]


- lexsort 对满足多个键的数组执行间接排序

In [142]:
a = np.array([3,2,6,4,5])
b = np.array([50,30,40,20,10])
c = np.array([400,300,600,100,200])
d = np.lexsort((a,b,c))
list(zip(a[d], b[d], c[d]))

[(4, 20, 100), (5, 10, 200), (2, 30, 300), (3, 50, 400), (6, 40, 600)]

In [143]:
a[d]

array([4, 5, 2, 3, 6])

- 去重

In [144]:
names = np.array(["小明","小黄", "小花","小明", "小花", "小李", "小白"])
np.unique(names)

array(['小明', '小李', '小白', '小花', '小黄'], 
      dtype='<U2')

In [145]:
sorted(set(names))

['小明', '小李', '小白', '小花', '小黄']

- 重复

In [146]:
arr = np.arange(5)
np.tile(arr,3)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [148]:
arr = np.arange(12).reshape(3,4)
arr.repeat(2, axis=0)

array([[ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [149]:
arr.repeat(2, axis=1)

array([[ 0,  0,  1,  1,  2,  2,  3,  3],
       [ 4,  4,  5,  5,  6,  6,  7,  7],
       [ 8,  8,  9,  9, 10, 10, 11, 11]])

- 统计

- axis = 0  横轴计算  将一列的结果算出来
- axis = 1  纵轴计算
- axis = 0  总值

In [150]:
arr = np.arange(20).reshape(4,5)
np.sum(arr)

190

In [153]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [151]:
arr.sum(axis=0)

array([30, 34, 38, 42, 46])

In [152]:
arr.sum(axis=1)

array([10, 35, 60, 85])

In [154]:
np.mean(arr)

9.5

In [155]:
np.mean(arr,axis=0)

array([  7.5,   8.5,   9.5,  10.5,  11.5])

In [156]:
np.std(arr)

5.7662812973353983

In [157]:
np.var(arr)

33.25

In [158]:
np.min(arr)

0

In [159]:
np.max(arr)

19

In [161]:
np.argmin(arr)# 最小值的索引

0

In [162]:
np.argmax(arr)

19

In [163]:
arr = np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
np.cumsum(arr) #计算所有元素的累计和，一步一步来算

array([ 2,  5,  9, 14, 20, 27, 35, 44], dtype=int32)

In [165]:
np.cumprod(arr)#计算所有元素的累计积

array([     2,      6,     24,    120,    720,   5040,  40320, 362880], dtype=int32)